{% set name = "stripy" %}
{% set version = "2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/underworldcode/{{ name|lower }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 956aa9bea6b71326185e66cbf094d1e422b8a5e899836fc68c07e26e9377fd6e

build:
  number: 0
  script:
    # Cross-compilation stuff vendored from numpy-feedstock
    # necessary for cross-compilation to point to the right env
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig                                    # [build_platform != target_platform]
    - echo "python = '${PREFIX}/bin/python'" >> ${CONDA_PREFIX}/meson_cross_file.txt  # [build_platform != target_platform]
    - MESON_ARGS_REDUCED="$(echo $MESON_ARGS | sed 's/--buildtype release //g')"  # [unix]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed . -Csetup-args=${MESON_ARGS_REDUCED// / -Csetup-args=}  # [unix]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .  # [not unix]

requirements:

  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python
    - ninja
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}

  host:
    - python
    - pip
    - numpy
    - meson-python
    - ninja

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.0.0

test:
  requires:
    - pytest
    - setuptools # for pkg_resources
    - numpy

  source_files:
    - stripy/tests

  commands:
    - pytest

about:
  home: https://github.com/underworldcode/stripy
  license: LGPL-2.0-or-later
  license_family: GPL
  license_file: COPYING.LESSER
  summary: Python interface to TRIPACK and STRIPACK fortran code for triangulation/interpolation in Cartesian coordinates and on a sphere
  doc_url: https://underworldcode.github.io/stripy/2.1.1
  dev_url: https://github.com/underworldcode/stripy

extra:
  recipe-maintainers:
    - lmoresi
    - brmather
    - rbeucher
