{% set name = "stripy" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/underworldcode/{{ name|lower }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4088ee6457eb5f885296b6ab89b5d11603dc3e12ba8480bed6a7f76b37bfc48c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}

  host:
    - python
    - pip
    - numpy

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.0.0

test:
  requires:
    - pytest
    - setuptools # for pkg_resources

  source_files:
    - tests

  commands:
    - pytest

about:
  home: https://github.com/underworldcode/stripy
  license: LGPL-2.0-or-later
  license_family: GPL
  license_file: COPYING.LESSER
  summary: Python interface to TRIPACK and STRIPACK fortran code for triangulation/interpolation in Cartesian coordinates and on a sphere
  doc_url: https://underworldcode.github.io/stripy/2.0.5b2
  dev_url: https://github.com/underworldcode/stripy

extra:
  recipe-maintainers:
    - lmoresi
    - brmather
    - rbeucher
